## Ejercicio 1

In [15]:
codigo = 140808
miLista = [int(n) for n in str(codigo//2)]
miLista

[7, 0, 4, 0, 4]

## Ejecicio 2

In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_gradient_magnitude
from wordcloud import WordCloud, ImageColorGenerator

In [2]:
url = 'https://www.senamhi.gob.pe/?&p=pronostico-meteorologico'
page = requests.get(url)
page.status_code

200

In [3]:
soup = BeautifulSoup(page.content,'html.parser')

In [4]:
lugar0 = []
for l in soup.select("#listaprono > table > tbody  tr > td > div:nth-child(1)"):
    lugar0.append(l.get_text())
lugar = []
for l in lugar0:
    for i in range(3):
        lugar.append(l)

In [5]:
#tabla de 3 filas 

fecha = []
for f in soup.select("#listaprono > table  tbody > tr > td div > div:nth-child(1)"):
    fecha.append(f.get_text())

In [6]:
tmax = []
for t in soup.select("#listaprono > table  tbody > tr > td div > div:nth-child(3)"):
    tmax.append(t.get_text())

In [7]:
tmin = []
for t in soup.select("#listaprono > table  tbody > tr > td div > div:nth-child(4)"):
    tmin.append(t.get_text())

In [8]:
descripcion = []
for d in soup.select("#listaprono > table  tbody > tr > td div > div:nth-child(5)"):
    descripcion.append(d.get_text())

In [9]:
df = pd.DataFrame({'Lugar':lugar,'Fecha':fecha,'Tmax':tmax,'Tmin':tmin,'Descripcion':descripcion})
df

,Lugar,Fecha,Tmax,Tmin,Descripcion
0,BAGUA GRANDE - AMAZONAS,"jueves, 04 de marzo",31ºC,18ºC,Cielo cubierto a cielo nublado durante el día...
1,BAGUA GRANDE - AMAZONAS,"viernes, 05 de marzo",31ºC,18ºC,Cielo cubierto variando a cielo nublado duran...
2,BAGUA GRANDE - AMAZONAS,"sábado, 06 de marzo",31ºC,18ºC,Cielo nublado entre cielo nublado parcial dur...
3,CHACHAPOYAS - AMAZONAS,"jueves, 04 de marzo",21ºC,12ºC,Cielo nublado hacia el mediodía a cielo cubie...
4,CHACHAPOYAS - AMAZONAS,"viernes, 05 de marzo",21ºC,11ºC,Cielo nublado por la mañana variando a cielo ...
...,...,...,...,...,...
814,PUERTO ESPERANZA - UCAYALI,"viernes, 05 de marzo",32ºC,22ºC,Cielo nublado parcial entre cielo con nubes d...
815,PUERTO ESPERANZA - UCAYALI,"sábado, 06 de marzo",31ºC,22ºC,Cielo nublado en las primeras horas de la mañ...
816,SAN ALEJANDRO - UCAYALI,"jueves, 04 de marzo",30ºC,20ºC,Cielo nublado entre cielo nublado parcial dur...
817,SAN ALEJANDRO - UCAYALI,"viernes, 05 de marzo",31ºC,20ºC,Cielo nublado en las primeras horas de la mañ...
818,SAN ALEJANDRO - UCAYALI,"sábado, 06 de marzo",30ºC,20ºC,Cielo nublado parcial variando a cielo nublad...

In [10]:
df['Tmed'] = [ (int(x[:-2])+int(n[:-2]))/2 for x,n in zip(df['Tmax'],df['Tmin'])]
df

,Lugar,Fecha,Tmax,Tmin,Descripcion,Tmed
0,BAGUA GRANDE - AMAZONAS,"jueves, 04 de marzo",31ºC,18ºC,Cielo cubierto a cielo nublado durante el día...,24.5
1,BAGUA GRANDE - AMAZONAS,"viernes, 05 de marzo",31ºC,18ºC,Cielo cubierto variando a cielo nublado duran...,24.5
2,BAGUA GRANDE - AMAZONAS,"sábado, 06 de marzo",31ºC,18ºC,Cielo nublado entre cielo nublado parcial dur...,24.5
3,CHACHAPOYAS - AMAZONAS,"jueves, 04 de marzo",21ºC,12ºC,Cielo nublado hacia el mediodía a cielo cubie...,16.5
4,CHACHAPOYAS - AMAZONAS,"viernes, 05 de marzo",21ºC,11ºC,Cielo nublado por la mañana variando a cielo ...,16.0
...,...,...,...,...,...,...
814,PUERTO ESPERANZA - UCAYALI,"viernes, 05 de marzo",32ºC,22ºC,Cielo nublado parcial entre cielo con nubes d...,27.0
815,PUERTO ESPERANZA - UCAYALI,"sábado, 06 de marzo",31ºC,22ºC,Cielo nublado en las primeras horas de la mañ...,26.5
816,SAN ALEJANDRO - UCAYALI,"jueves, 04 de marzo",30ºC,20ºC,Cielo nublado entre cielo nublado parcial dur...,25.0
817,SAN ALEJANDRO - UCAYALI,"viernes, 05 de marzo",31ºC,20ºC,Cielo nublado en las primeras horas de la mañ...,25.5
818,SAN ALEJANDRO - UCAYALI,"sábado, 06 de marzo",30ºC,20ºC,Cielo nublado parcial variando a cielo nublad...,25.0

In [11]:
import hashlib

df['hash256_desc'] = [hashlib.sha256(d.encode('utf-8')).hexdigest() for d in df['Descripcion']]

In [12]:
#reordenando
df = df[['Lugar', 'Fecha', 'Tmax', 'Tmin', 'Tmed', 'hash256_desc']]
df

,Lugar,Fecha,Tmax,Tmin,Tmed,hash256_desc
0,BAGUA GRANDE - AMAZONAS,"jueves, 04 de marzo",31ºC,18ºC,24.5,48a117d94f163cd687f7cc3c7abc54b49052cb5202c63c...
1,BAGUA GRANDE - AMAZONAS,"viernes, 05 de marzo",31ºC,18ºC,24.5,abe96acfbf19a25c28558516846cc40ddb4e403bf5abef...
2,BAGUA GRANDE - AMAZONAS,"sábado, 06 de marzo",31ºC,18ºC,24.5,6d655315a2091ff463c3a25651bd4fb8e389fc9e2858fb...
3,CHACHAPOYAS - AMAZONAS,"jueves, 04 de marzo",21ºC,12ºC,16.5,8812aad56c6b601523abb8bf815798a966807c91aa131b...
4,CHACHAPOYAS - AMAZONAS,"viernes, 05 de marzo",21ºC,11ºC,16.0,9df574dc535c9f65dcae8ddf679dd33be8c0a6ffaf1e58...
...,...,...,...,...,...,...
814,PUERTO ESPERANZA - UCAYALI,"viernes, 05 de marzo",32ºC,22ºC,27.0,6089733d12ab7a15b67bc5ac2024bb9dd87582f933d712...
815,PUERTO ESPERANZA - UCAYALI,"sábado, 06 de marzo",31ºC,22ºC,26.5,c8b8f833f9d1e18a2bd9d3f95bd8fc5e9c5777a7a01e7e...
816,SAN ALEJANDRO - UCAYALI,"jueves, 04 de marzo",30ºC,20ºC,25.0,edff6061c4e8de49e43cb59302f88350201268b3f8e713...
817,SAN ALEJANDRO - UCAYALI,"viernes, 05 de marzo",31ºC,20ºC,25.5,c8b8f833f9d1e18a2bd9d3f95bd8fc5e9c5777a7a01e7e...
818,SAN ALEJANDRO - UCAYALI,"sábado, 06 de marzo",30ºC,20ºC,25.0,6159eb0c9d2d20104d5e003e683670c5ad5cb127487d10...

In [13]:
df.to_excel('df2.xlsx',sheet_name='Sheet1')

In [14]:
!ls

df2.xlsx  examen2.ipynb

## Ejercicio 3

In [15]:
data = pd.read_csv('data.csv')
data

,Ap Paterno,Ap Materno,Nombre,geolocation_lat,geolocation_lng,x,categoria,clave,hash512
0,YATACO,RAMIREZ,LUIS ALBERTO,-15.8320,-70.0225,NaN,NaN,NaN,NaN
1,DELGADO,DE LA CRUZ,NANCY MARIA,-15.8320,-70.0222,NaN,NaN,NaN,NaN
2,CCANTO,CHOCCE,FELICIANO,-15.8313,-70.0211,NaN,NaN,NaN,NaN
3,LUYO,TAKAYAMA,EDUARDO,-15.8314,-70.0206,NaN,NaN,NaN,NaN
4,RIVERA,GUILLEN,DANIEL ALCIDES,-15.8303,-70.0201,NaN,NaN,NaN,NaN
5,CALDERON,MALDONADO,PATRICIA ROSSANA,-15.8303,-70.0199,NaN,NaN,NaN,NaN
6,ROSILLO,JUAREZ,JESSICA GIANINA,-15.8303,-70.0191,NaN,NaN,NaN,NaN
7,SAMANIEGO,ORELLANA,JESUS,-15.8290,-70.0183,NaN,NaN,NaN,NaN
8,SILVA,QUINTEROS,GLORIA ELENA,-15.8290,-70.0171,NaN,NaN,NaN,NaN
9,VILLANUEVA,CASTAÑEDA,MARIA DOLORES,-15.8236,-70.0204,NaN,NaN,NaN,NaN
10,SEGURA,CASTILLA,CARLOS JESUS,-15.8237,-70.0208,NaN,NaN,NaN,NaN
11,FERNANDEZ,PAUCAR,GLORIA MARIBEL,-15.8222,-70.0204,NaN,NaN,NaN,NaN
12,MAYURI,CAMPOS,BETTY FLOR,-15.8216,-70.0223,NaN,NaN,NaN,NaN
13,PORTAL,CACHI,ELVESI CONSUELO,-15.8217,-70.0216,NaN,NaN,NaN,NaN
14,BALDEON,BALDEON,YRMA YRENE,-15.8229,-70.0089,NaN,NaN,NaN,NaN
15,CHANGANA,AGUILAR,BEATRIZ ARACELI,-15.8233,-70.0086,NaN,NaN,NaN,NaN
16,ALMEYDA,MEDINA,DANIEL ANGEL,-15.8236,-70.0079,NaN,NaN,NaN,NaN
17,VASQUEZ,ACEVEDO,ROSA TRINIDAD,-15.8336,-70.0186,NaN,NaN,NaN,NaN
18,SANCHEZ,GUTIERREZ,BERTILA HORTENCIA,-15.8338,-70.0185,NaN,NaN,NaN,NaN
19,MEJIA,MEZA,SARA LUZ,-15.8339,-70.0185,NaN,NaN,NaN,NaN
20,CORBERA,ANDERSON,ROSA MARIA,-15.8341,-70.0185,NaN,NaN,NaN,NaN
21,CHAVEZ,RIVERA,YSABEL PATRICIA,-15.8343,-70.0183,NaN,NaN,NaN,NaN
22,PONCE,PARDO,MYRIAM DELIA,-15.8344,-70.0183,NaN,NaN,NaN,NaN
23,ALARCON,HINOSTROZA,EMILIA ADELA,-15.8345,-70.0184,NaN,NaN,NaN,NaN
24,AQUIJE,TIPIANA,OLGA ELIZABETH,-15.8346,-70.0185,NaN,NaN,NaN,NaN
25,MORENO,HUAMANI,LUCY FERMINA,-15.8346,-70.0183,NaN,NaN,NaN,NaN
26,JURADO,CHAPARRO DE CRIVILLERO,LUZ ANDREA,-15.8323,-70.0164,NaN,NaN,NaN,NaN
27,BACA,VILLAFUERTE,MARILUZ RICARDINA,-15.8325,-70.0163,NaN,NaN,NaN,NaN
28,MENDOZA,LLAJA,LAURA,-15.8304,-70.0157,NaN,NaN,NaN,NaN
29,SEGOVIA,MALDONADO,ISABEL FELICITA,-15.8289,-70.0173,NaN,NaN,NaN,NaN
30,VILLAVICENCIO,MERLIN,MARIA LAURA,-15.8290,-70.0176,NaN,NaN,NaN,NaN
31,CORIMANYA,MANSILLA,MARLENE MONICA,-15.8291,-70.0179,NaN,NaN,NaN,NaN

In [16]:
data['x'] = np.random.randint(1,6,size=len(data))

In [17]:
categorias = ['','C','C#','Python','JavaScript','Go']

data['categoria'] = [ categorias[r] for r in data['x'] ]
data

,Ap Paterno,Ap Materno,Nombre,geolocation_lat,geolocation_lng,x,categoria,clave,hash512
0,YATACO,RAMIREZ,LUIS ALBERTO,-15.8320,-70.0225,4,JavaScript,NaN,NaN
1,DELGADO,DE LA CRUZ,NANCY MARIA,-15.8320,-70.0222,2,C#,NaN,NaN
2,CCANTO,CHOCCE,FELICIANO,-15.8313,-70.0211,3,Python,NaN,NaN
3,LUYO,TAKAYAMA,EDUARDO,-15.8314,-70.0206,5,Go,NaN,NaN
4,RIVERA,GUILLEN,DANIEL ALCIDES,-15.8303,-70.0201,5,Go,NaN,NaN
5,CALDERON,MALDONADO,PATRICIA ROSSANA,-15.8303,-70.0199,4,JavaScript,NaN,NaN
6,ROSILLO,JUAREZ,JESSICA GIANINA,-15.8303,-70.0191,4,JavaScript,NaN,NaN
7,SAMANIEGO,ORELLANA,JESUS,-15.8290,-70.0183,4,JavaScript,NaN,NaN
8,SILVA,QUINTEROS,GLORIA ELENA,-15.8290,-70.0171,2,C#,NaN,NaN
9,VILLANUEVA,CASTAÑEDA,MARIA DOLORES,-15.8236,-70.0204,4,JavaScript,NaN,NaN
10,SEGURA,CASTILLA,CARLOS JESUS,-15.8237,-70.0208,2,C#,NaN,NaN
11,FERNANDEZ,PAUCAR,GLORIA MARIBEL,-15.8222,-70.0204,3,Python,NaN,NaN
12,MAYURI,CAMPOS,BETTY FLOR,-15.8216,-70.0223,1,C,NaN,NaN
13,PORTAL,CACHI,ELVESI CONSUELO,-15.8217,-70.0216,4,JavaScript,NaN,NaN
14,BALDEON,BALDEON,YRMA YRENE,-15.8229,-70.0089,2,C#,NaN,NaN
15,CHANGANA,AGUILAR,BEATRIZ ARACELI,-15.8233,-70.0086,1,C,NaN,NaN
16,ALMEYDA,MEDINA,DANIEL ANGEL,-15.8236,-70.0079,4,JavaScript,NaN,NaN
17,VASQUEZ,ACEVEDO,ROSA TRINIDAD,-15.8336,-70.0186,5,Go,NaN,NaN
18,SANCHEZ,GUTIERREZ,BERTILA HORTENCIA,-15.8338,-70.0185,5,Go,NaN,NaN
19,MEJIA,MEZA,SARA LUZ,-15.8339,-70.0185,2,C#,NaN,NaN
20,CORBERA,ANDERSON,ROSA MARIA,-15.8341,-70.0185,5,Go,NaN,NaN
21,CHAVEZ,RIVERA,YSABEL PATRICIA,-15.8343,-70.0183,4,JavaScript,NaN,NaN
22,PONCE,PARDO,MYRIAM DELIA,-15.8344,-70.0183,1,C,NaN,NaN
23,ALARCON,HINOSTROZA,EMILIA ADELA,-15.8345,-70.0184,3,Python,NaN,NaN
24,AQUIJE,TIPIANA,OLGA ELIZABETH,-15.8346,-70.0185,2,C#,NaN,NaN
25,MORENO,HUAMANI,LUCY FERMINA,-15.8346,-70.0183,1,C,NaN,NaN
26,JURADO,CHAPARRO DE CRIVILLERO,LUZ ANDREA,-15.8323,-70.0164,5,Go,NaN,NaN
27,BACA,VILLAFUERTE,MARILUZ RICARDINA,-15.8325,-70.0163,2,C#,NaN,NaN
28,MENDOZA,LLAJA,LAURA,-15.8304,-70.0157,5,Go,NaN,NaN
29,SEGOVIA,MALDONADO,ISABEL FELICITA,-15.8289,-70.0173,2,C#,NaN,NaN
30,VILLAVICENCIO,MERLIN,MARIA LAURA,-15.8290,-70.0176,2,C#,NaN,NaN
31,CORIMANYA,MANSILLA,MARLENE MONICA,-15.8291,-70.0179,2,C#,NaN,NaN

In [18]:
hashes = []
claves = []
for i in range(len(data)):
    clave = data.iloc[i]['Ap Paterno'][:2] + data.iloc[i]['Ap Materno'][:2] + str(data.iloc[i]['x']) + data.iloc[i]['categoria']
    hashes.append(hashlib.sha512(clave.encode('utf-8')).hexdigest())
    claves.append(clave)
data['hash512'] = hashes
data['clave'] = claves

In [19]:
data

,Ap Paterno,Ap Materno,Nombre,geolocation_lat,geolocation_lng,x,categoria,clave,hash512
0,YATACO,RAMIREZ,LUIS ALBERTO,-15.8320,-70.0225,4,JavaScript,YARA4JavaScript,13eef4bd3bd5c5490292573db73ff71951b1efa179913c...
1,DELGADO,DE LA CRUZ,NANCY MARIA,-15.8320,-70.0222,2,C#,DEDE2C#,aef7623f13af04befbbc5df162df005a7c24214949de9c...
2,CCANTO,CHOCCE,FELICIANO,-15.8313,-70.0211,3,Python,CCCH3Python,684c5717dc39a72a84c564f6fa3d37829006ff2c73a696...
3,LUYO,TAKAYAMA,EDUARDO,-15.8314,-70.0206,5,Go,LUTA5Go,909c0dc8372de5246633f08186be034fb5003d41ba45fb...
4,RIVERA,GUILLEN,DANIEL ALCIDES,-15.8303,-70.0201,5,Go,RIGU5Go,d5f26fbdb0f2c250198d8b29fcfe061b53cc975d7feb00...
5,CALDERON,MALDONADO,PATRICIA ROSSANA,-15.8303,-70.0199,4,JavaScript,CAMA4JavaScript,16a3336682de395ee3e7e27af90479c544c0e07737005b...
6,ROSILLO,JUAREZ,JESSICA GIANINA,-15.8303,-70.0191,4,JavaScript,ROJU4JavaScript,e6b2b99995dd634742f9be0b68237f57adc1a19e813665...
7,SAMANIEGO,ORELLANA,JESUS,-15.8290,-70.0183,4,JavaScript,SAOR4JavaScript,9fa4ab62f27996a00c74bdea224e223dce0144cf5110e3...
8,SILVA,QUINTEROS,GLORIA ELENA,-15.8290,-70.0171,2,C#,SIQU2C#,3916e08800c48119818a2c81f68ea1e4ada9c267080b51...
9,VILLANUEVA,CASTAÑEDA,MARIA DOLORES,-15.8236,-70.0204,4,JavaScript,VICA4JavaScript,306388e97f1735a7d74883b7b4139905d341a85a84c76a...
10,SEGURA,CASTILLA,CARLOS JESUS,-15.8237,-70.0208,2,C#,SECA2C#,9574a0ca81871ef9ecc7f8fcb81bc3632f10ffa25f3284...
11,FERNANDEZ,PAUCAR,GLORIA MARIBEL,-15.8222,-70.0204,3,Python,FEPA3Python,723e56af2a2ffc4b214467bf56ef77c8cd10929b83d89f...
12,MAYURI,CAMPOS,BETTY FLOR,-15.8216,-70.0223,1,C,MACA1C,d58d22dd2e5a4f9aaf3051057eb377bd87b847fe54037d...
13,PORTAL,CACHI,ELVESI CONSUELO,-15.8217,-70.0216,4,JavaScript,POCA4JavaScript,5384279c460e8c55569f8fdc1beb644be45d789282b59e...
14,BALDEON,BALDEON,YRMA YRENE,-15.8229,-70.0089,2,C#,BABA2C#,a36424390bf713083554a75fee7ff256da22261fe87e40...
15,CHANGANA,AGUILAR,BEATRIZ ARACELI,-15.8233,-70.0086,1,C,CHAG1C,97db222897b91372593c255e59d29ad1630f067f4daeef...
16,ALMEYDA,MEDINA,DANIEL ANGEL,-15.8236,-70.0079,4,JavaScript,ALME4JavaScript,58e5000a1f2686082a259a3eba9b01a013a866ac2f82f2...
17,VASQUEZ,ACEVEDO,ROSA TRINIDAD,-15.8336,-70.0186,5,Go,VAAC5Go,5087d03454a5688d9cd799902d5be4d174af137fa9253a...
18,SANCHEZ,GUTIERREZ,BERTILA HORTENCIA,-15.8338,-70.0185,5,Go,SAGU5Go,734a397ca549fd96e6f1420d346adfa2554f08e0aca2e4...
19,MEJIA,MEZA,SARA LUZ,-15.8339,-70.0185,2,C#,MEME2C#,3025331594e2db93064f009dc7fc43d435787fac06497a...
20,CORBERA,ANDERSON,ROSA MARIA,-15.8341,-70.0185,5,Go,COAN5Go,d9a4f1f1c70e0c778de14949e6a1d7d5b664064a622070...
21,CHAVEZ,RIVERA,YSABEL PATRICIA,-15.8343,-70.0183,4,JavaScript,CHRI4JavaScript,5b378c0a72f56651a37c000e1495409b18be721dbba1b9...
22,PONCE,PARDO,MYRIAM DELIA,-15.8344,-70.0183,1,C,POPA1C,37e9e2b5d1d1f1d3d29939669b72b3a692157f40d3b7f8...
23,ALARCON,HINOSTROZA,EMILIA ADELA,-15.8345,-70.0184,3,Python,ALHI3Python,25a54d8c14875bb7136465826ef98e77b3b19bb0843d19...
24,AQUIJE,TIPIANA,OLGA ELIZABETH,-15.8346,-70.0185,2,C#,AQTI2C#,0f62699557635f3e4fae3714beb3ede446d3e9a4f41f39...
25,MORENO,HUAMANI,LUCY FERMINA,-15.8346,-70.0183,1,C,MOHU1C,be2bd2710aeda7f04fb5606c604fc46de4b9bc5689ddb6...
26,JURADO,CHAPARRO DE CRIVILLERO,LUZ ANDREA,-15.8323,-70.0164,5,Go,JUCH5Go,869761e80763a3459a09ee2932c6c914211f33b4aecc82...
27,BACA,VILLAFUERTE,MARILUZ RICARDINA,-15.8325,-70.0163,2,C#,BAVI2C#,b908dc5f197d8ff827ba1c98115c7238b2d6faaacfbf18...
28,MENDOZA,LLAJA,LAURA,-15.8304,-70.0157,5,Go,MELL5Go,e5644e9b8d5d4dd52c00aedbc06e615bfb45493593c63c...
29,SEGOVIA,MALDONADO,ISABEL FELICITA,-15.8289,-70.0173,2,C#,SEMA2C#,a6f031d7b91e8e8e1f9f3c63c05402d35c838f532a559c...
30,VILLAVICENCIO,MERLIN,MARIA LAURA,-15.8290,-70.0176,2,C#,VIME2C#,3bfef7672e778da07f4137c30d38f7bef0562be122759e...
31,CORIMANYA,MANSILLA,MARLENE MONICA,-15.8291,-70.0179,2,C#,COMA2C#,5ddf34162d5fbd2dba9e7fa98ed9f09ea8f4745dcbbded...

## Ejercicio 4

In [22]:
import os 

class Banco:
    def __init__(self,nombre):
        self.nombre = nombre
        self.cola = []
        self.clientes = []
    def llegada(self,data):
        if data['preferencia'] == 1:
            self.cola.insert(0,data)
        else:
            self.cola.append(data)
    def getCola(self):
        return self.cola
    def atenderCliente(self):
        if (len(self.cola)) == 0:
            print('no existen mas clientes')
        else:
            print('atendiendo ..')
            os.system('sleep 0.5')
            print('cliente atendido y eliminado de la cola \n',self.cola[0])
            # una persona sera cliente una vez es atendido.
            self.clientes.append(self.cola[0])
            ## eliminando al cliente de la cola 
            del self.cola[0]
    def buscarCliente(self,dni):
        # buscando solamente a clientes que ya se atendieron almenos una vez.
        #utilizando busqueda secuencial
        for cliente in self.clientes:
            if cliente['DNI'] == dni:
                return cliente
                break
        return "cliente no encontrado"

In [23]:
banco_cpp = Banco('banco de la nacion')
## ingresando valores manualmente

banco_cpp.llegada({'Apellidos': 'yataco ramirez', 'Nombres': 'luis alberto', 'DNI': 33, 'preferencia': 1})
banco_cpp.llegada({'Apellidos': 'luyo takayama', 'Nombres': 'eduardo', 'DNI': 44, 'preferencia': 0})
banco_cpp.llegada({'Apellidos': 'calderon maldonado', 'Nombres': 'patricia rossana', 'DNI': 331, 'preferencia': 1})

##
while True:
    print("""
    • 1 = Llegada de cliente
    • 2 = Llegada de cliente preferencial
    • 3 = Atención de cliente
    • 4 = Búsqueda de cliente
    • 5 = Limpiar consola
    • 0 = Fin de eventos
    """)
    opcion = int(input("> "))
    if opcion in [1,2]: 
        #pidiendo los datos al cliente.
        data = {
            'Apellidos':None,
            'Nombres':None,
            'DNI':None,
        }
        for key in data.keys():
            print("ingrese %s :" %key,end='')
            data[key] = input()
        data['DNI'] = int(data['DNI'])
        data['preferencia'] = opcion - 1 
        banco_cpp.llegada(data)
        print('\nCola actualizada:')
        for c in banco_cpp.getCola():
            print(c)
        print()
    elif opcion == 3:
        banco_cpp.atenderCliente()

    elif opcion == 4:
        dni = int(input('ingrese un dni: '))
        resultado = banco_cpp.buscarCliente(dni)
        print(resultado)

    elif opcion == 5:
        os.system('clear')

    elif opcion == 5:
        break
    elif opcion == 0:
        break
    else:
        pass

    • 1 = Llegada de cliente
    • 2 = Llegada de cliente preferencial
    • 3 = Atención de cliente
    • 4 = Búsqueda de cliente
    • 5 = Limpiar consola
    • 0 = Fin de eventos

>  1

ingrese Apellidos :

 mendoza quispe

ingrese Nombres :

 julio

ingrese DNI :

 87654321

Cola actualizada:
{'Apellidos': 'calderon maldonado', 'Nombres': 'patricia rossana', 'DNI': 331, 'preferencia': 1}
{'Apellidos': 'yataco ramirez', 'Nombres': 'luis alberto', 'DNI': 33, 'preferencia': 1}
{'Apellidos': 'luyo takayama', 'Nombres': 'eduardo', 'DNI': 44, 'preferencia': 0}
{'Apellidos': 'mendoza quispe', 'Nombres': 'julio', 'DNI': 87654321, 'preferencia': 0}


    • 1 = Llegada de cliente
    • 2 = Llegada de cliente preferencial
    • 3 = Atención de cliente
    • 4 = Búsqueda de cliente
    • 5 = Limpiar consola
    • 0 = Fin de eventos

>  3

atendiendo ..
cliente atendido y eliminado de la cola
 {'Apellidos': 'calderon maldonado', 'Nombres': 'patricia rossana', 'DNI': 331, 'preferencia': 1}

    • 1 = Llegada de cliente
    • 2 = Llegada de cliente preferencial
    • 3 = Atención de cliente
    • 4 = Búsqueda de cliente
    • 5 = Limpiar consola
    • 0 = Fin de eventos

>  4
ingrese un dni:  331

{'Apellidos': 'calderon maldonado', 'Nombres': 'patricia rossana', 'DNI': 331, 'preferencia': 1}

    • 1 = Llegada de cliente
    • 2 = Llegada de cliente preferencial
    • 3 = Atención de cliente
    • 4 = Búsqueda de cliente
    • 5 = Limpiar consola
    • 0 = Fin de eventos

>  0